### ISSUE TITLE
Game Logic

### ISSUE THREAD

**Issue by shrutirao94** [shaw-rohit/SoftwareTesting2020#10]
The logic for the basic Hangman game does the following:
1. Picks a word for the user to guess
2. Checks users guesses against valid letters
3. Updates count of attempts based on incorrect guess
4. Reveals the letters that make up the word on correct guess 
5. Concludes game when either user is out of moves or if user is able to correctly guess the word
6. Allows user to quit at any given time

**Comment by arumoy-shome** [comment]
I feel that we need this before we can implement other features, it's really hard to make design decisions regarding the feature I am working on without a starting point (I need to see how Shruti is going to structure the files, naming convention, etc.). Maybe it is just me? What do you guys think?

@shaw-rohit @Pungent-Paws.

**Comment by Pungent-Paws** [comment]
> I feel that we need this before we can implement other features, it's really hard to make design decisions regarding the feature I am working on without a starting point (I need to see how Shruti is going to structure the files, naming convention, etc.). Maybe it is just me? What do you guys think?
> 
> @shaw-rohit @Pungent-Paws.
Yeah I'd say so too, you need some sorta game backbone to implement score viewing, else you'll end up using placeholders to eventually change them all, having to restructure etc? Not sure what solution to propose though hmm

**Comment by shrutirao94** [comment]
I think scoring should be a feature for improving the game. You don't really need it for the first Sprint. My code informs the user if they won or lost at this time.

**Comment by shaw-rohit** [comment]
Agree with @arumoy-shome. A common naming convention would be the way to go.

Also, I think the issues "Game conclusion" and "Win/lose game" are part of the main game logic which @shrutirao94 has already implemented in her code, so we don't need those anymore.

**Comment by arumoy-shome** [comment]
Closed in #13.
