### ISSUE TITLE
Python does not pick up venv Python 3.7

### ISSUE THREAD

**Issue by shrutirao94** [shaw-rohit/SoftwareTesting2020#11]
I cloned the repo and activated the virtual environment. However I noted that:

`which python` pointed to _local\bin\python_ which is **Python 2.7**

<img width="511" alt="Screenshot 2020-04-15 at 19 37 57" src="https://user-images.githubusercontent.com/12822003/79369085-b2142f80-7f50-11ea-8ba8-45856c253faf.png">

I had to remove the _venv_ directory and recreate it myself to resolve the issue. 

My Specs:
Fish Shell
MacOS Catalina 10.15.4

**Comment by shaw-rohit** [comment]
That's strange. Invoking 'python' in the venv gives me Python 3.7.4 to work with.

![image](https://user-images.githubusercontent.com/40485926/79370768-89416980-7f53-11ea-9fc5-262ac0ffa46d.png)

Specs (work laptop):
Hyper terminal
Windows 10 v1903

I'll test it on my personal laptop (Windows as well as Ubuntu) and post an update on my findings.

**Comment by shaw-rohit** [comment]
...and here's Ubuntu 19.03 on the default terminal. 
`which python` doesn't seem to work and the python version (`python2` or `python3`) needs to be specified for everything, but I guess this doesn't leave room for any version error on Linux.

![image](https://user-images.githubusercontent.com/40485926/79374451-a11aec80-7f57-11ea-83fa-2b1c1e77b99d.png)

**Comment by arumoy-shome** [comment]
Strange, this method worked in previous projects. I guess easiest fix is to simply create the venv using python 3.7.x yourself and we remove the venv directory from the repo.

**Comment by Pungent-Paws** [comment]
> Strange, this method worked in previous projects. I guess easiest fix is to simply create the venv using python 3.7.x yourself and we remove the venv directory from the repo.

Yeah probably. I got a (bit of a different) issue too; there is no .bat file in /bin, which I think is the only way the venv can be activated in Windows 10 (my only device).

**Comment by shaw-rohit** [comment]
Good point. Perhaps we should create the virtual environment on Windows since the .bat file will also be generated alongside the others.
