### ISSUE TITLE
The dashes generated for the user could show a random letter

### ISSUE THREAD

**Issue by shrutirao94** [shaw-rohit/SoftwareTesting2020#14]
The first time the game prints the dashes for the user, they are all blank. A random letter could be instead displayed as a more intuitive and helpful design.

**Comment by shaw-rohit** [comment]
This feature could be implemented if and when we introduce difficulty levels. For example:

- Easy - 2 letters printed
- Medium - 1 letter printed
- Hard - No letters printed

Else an example would be present in the game instructions anyway.

**Comment by arumoy-shome** [comment]
We decided not to add features, instead focus on testing.
