### ISSUE TITLE
Remaining goals sprint 1

### ISSUE THREAD

**Issue by Pungent-Paws** [shaw-rohit/SoftwareTesting2020#17]
Hi, 

I just took a look at all your work so far, looks great (especially loving the hangman sign, Rohit)! I believe that all sprint 1 issues either already have been taken care of, or were unassigned but naturally already incorporated into the game logic (#10 ) and (OOP based) instructions (#1 ). Wondering what are remaining (existing or not yet created) issues for sprint 1?

If I'm looking correctly, I believe the OOP based branches as-OOP and rs-instructions are still missing unit tests (even though they are bug free now as far as I could tell)?

If so, would these unit tests be something we'd like to have by the deadline of sprint 1? Or, would we be more excited about having more features added to sprint 1 (move some issues to sprint 1 that we would have saved for sprint 2 or 2.5), or do we prefer only adding such upgrades to the basic game after an opportunity to discuss them over a meeting? 

edit:
oh wait I think I should tag? @shrutirao94  @arumoy-shome  @shaw-rohit @Pungent-Paws

**Comment by arumoy-shome** [comment]
I think adding unit tests for the OOP implementation can be part of sprint 2 along with new features (although not sure what they are, perhaps something to discuss during our meeting tomorrow).
